version: '3'

services:
# https://prometheus.io/docs/prometheus/latest/installation/
  prometheus:
    image: prom/prometheus:v2.43.0   
    privileged: true
    volumes:
      - ./prometheus/etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/prometheus
    ports:
      - "9090:9090"
    restart: always

#https://grafana.com/docs/grafana/latest/setup-grafana/installation/docker/
  grafana: 
    image: grafana/grafana:9.2.15
    volumes:
      - ./grafana/data_grafana:/var/lib/grafana
      - ./grafana/config:/etc/grafana
      - ./grafana/config/provisioning:/etc/grafana/provisioning
    env_file:
      - ./grafana/config/config.monitoring
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    restart: always
  
#https://hub.docker.com/r/prom/blackbox-exporter/
  blackbox_exporter:
    image: prom/blackbox-exporter:v0.23.0
    volumes:
      - ./blackbox_exporter/blackbox.yml:/config/blackbox.yml
    command:
      - '--config.file=/config/blackbox.yml'
    ports:
      - 9115:9115
    restart: always